/* CREATING */

use bowling_app;
create table  users (
user_id int auto_increment primary key,
last_name varchar(50) NOT NULL,
first_name varchar(50) NOT NULL,
birthday date NOT NULL,
email varchar(50) unique NOT NULL,
nationality varchar(50)
);

create table  tournaments (
tournament_id int auto_increment primary key,
title varchar(255) NOT NUll,
information text
);

create table  payments (
payment_id int auto_increment primary key,
user_id int NOT NULL,
amount decimal(5,2) NOT NULL,
payment_date datetime NOT NULL,
tournament_id int NOT NULL,
foreign key (user_id) references users(user_id),
foreign key (tournament_id) references tournaments(tournament_id)
);

create table  bowling_alley (
alley_id int auto_increment unique primary key,
country varchar(255) NOT NUll,
address varchar(255) NOT NUll
);

create table  alley_lines (
line_id int auto_increment unique primary key,
line_num int NOT NUll,
alley_id int NOT NUll,
foreign key (alley_id) references bowling_alley(alley_id)
);

create table  games (
game_id int auto_increment primary key,
user_id int NOT NULL,
alley_id int NOT NULL,
line_id int NOT NULL,
score int,
tournament_id int NOT NULL,
foreign key (user_id) references users(user_id),
foreign key (alley_id) references bowling_alley(alley_id),
foreign key (line_id) references alley_lines(line_id),
foreign key (tournament_id) references tournaments(tournament_id)
);

/* UPDATING */
Alter table bowling_alley 
add column name varchar(55) NOT NULL;

/* INSERTING */

INSERT INTO users(first_name,last_name,birthday,email,nationality) values
('Igor','Player1','1992-01-04','facebook_4722@id.com','Ukraine' ),
('Osku', 'Player2', '1985-01-05','Osku@id.com','Finland'),
('Rihards', 'Player3','2003-01-06','Rihards7@id.com','Latvia'),
('Ben','Player4','2004-01-07','facebook_8215@id.com','United Kingdom'),
('Cedric','Player5','1986-01-08','didic76@id.com','France'),
('Ashleigh','Player6','1996-01-09','Ashleigh691@id.com','Scotland');

INSERT INTO bowling_alley(name,country,address) values
('Lucky Strike', 'Ukraine','Shevchenka BLvd,208/1,Cherkasy,Cherkasy Oblast,Ukraine'),
("John Scott's Partille", "Sweden", "Partille, Arenatorget 1,433 38"),
("Ice Bowl","United Kingdom", "Belfast, Old Dundonald RD 111"),
("Bowlero","Latvia", "Lielirbes street 27" ),
("Star Bowling", "Germany", "Am GroBmarkt 8, 555218 Ingelheim am Rhein"),
("La Bowl Ayr", "Scotland", "17 Miller Rd, Yar Ka7 2AX"),
("Bowling Plaza Grand-Quevilly", "France", "France,76120 Le Grand-Quevilldy, 22 boulevard Pierra Brossolette" ),
("Galeria Bowling", "Slovakia" , "Galeraibowling Kovise Toryska 5 05054011 Kosice Slovakia"),
("Bowling Della Martesna","Italy","Itali,20060 Pesssano con Bornago Mi , strada Provinciale 31"),
("Zemangale Bowling" , "Latvia", "Latvia, Jelgava, Skautuu Street 2");

INSERT INTO alley_lines(line_num,alley_id)  values
(3,2),
(8,2),
(9,2),
(12,3),
(13,3),
(14,3),
(7,4),
(8,4),
(1,5),
(2,5),
(3,5),
(4,5),
(5,5),
(11,6),
(12,6),
(4,7),
(5,7),
(3,8),
(5,9),
(6,9),
(16,10),
(17,10),
(18,10);

INSERT INTO tournaments values
(1,"Major Cup","some text"),
(2, "PBA Open Summer Clash","free text");

INSERT INTO bowling_app.payments 
SELECT payment_id, customer_id,amount,payment_date, staff_id FROM sakila.payment
limit 175;

insert into games(user_id,alley_id,line_id,score,tournament_id)
SELECT FLOOR(RAND()*(7-1+1))+1,
FLOOR(RAND()*(10-1+1))+1,
FLOOR(RAND()*(25-1+1))+1,
FLOOR(RAND()*(300-175+1))+175,
FLOOR(RAND()*(2-1+1))+1; /* Повторити Х-n разів */

/* UPDATE  
 values to correct  in relationship with autogenerated random data */
Update games
SET line_id = 2
WHERE game_id = 1 ;

Update games
SET line_id = 19
WHERE game_id = 3 ;

Update games
SET line_id = 18
WHERE game_id = 5 ;

Update games
SET line_id = 11
WHERE game_id = 6;

Update games
SET line_id = 21
WHERE game_id = 7;

Update games
SET line_id = 24
WHERE game_id = 8;

Update games
SET line_id = 18
WHERE game_id = 9;

Update games
SET line_id = 19
WHERE game_id = 10;

Update games
SET line_id = 15
WHERE game_id = 11;

/* REVIEW */

SELECT * FROM bowling_app.bowling_alley
where country like "Latvia";

insert into alley_lines  values
(1,1,1),
(2,2,11);

insert into alley_lines(line_num,alley_id)  values
('null','null');
